# Generated by Django 6.0.6 on 2026-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Challenges at the same level can be done in any order. Complete all challenges at level N to unlock level N+1.",
            ),
        ),
    ]
