# Generated by Django 6.0.6 on 2026-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_challenge_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
