# Generated by Django 6.0.6 on 2026-07-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_story_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("novice", "Novice"),
                    ("script-kiddie", "Script-Kiddie"),
                    ("analyst", "Analyst"),
                    ("operator", "Operator"),
                    ("cyber-spy", "Cyber-Spy"),
                    ("infiltrator", "Infiltrator"),
                    ("elite-hacker", "Elite Hacker"),
                    ("enigma-master", "Enigma Master"),
                ],
                default="novice",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("novice", "Novice"),
                    ("script-kiddie", "Script-Kiddie"),
                    ("analyst", "Analyst"),
                    ("operator", "Operator"),
                    ("cyber-spy", "Cyber-Spy"),
                    ("infiltrator", "Infiltrator"),
                    ("elite-hacker", "Elite Hacker"),
                    ("enigma-master", "Enigma Master"),
                ],
                default="novice",
                max_length=20,
            ),
        ),
    ]
