# Generated by Django 6.0.6 on 2026-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_challenge_difficulty_alter_story_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="difficulty",
        ),
    ]
