# Generated by Django 6.0.6 on 2026-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_challenge_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="answer_format",
            field=models.CharField(
                blank=True,
                help_text="Shows the expected answer format. Leave blank to auto-generate from the flag.",
                max_length=255,
            ),
        ),
    ]
