# Generated by Django 6.0.6 on 2026-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_migrate_legacy_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="answer_format",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="flag",
        ),
    ]
