# Generated by Django 6.0.6 on 2026-07-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_legacy_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userprogression",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userprogression",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="userprogression",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChallengeFile",
        ),
        migrations.DeleteModel(
            name="UserProgression",
        ),
    ]
